### ISSUE TITLE
Auto-generate initiative rolls for non-Hero participants

### ISSUE THREAD

**Issue by mannenen** [SickJumpsSoftware/RollInish#6]

**Comment by zatoseyes** [comment]
Good idea! If we make the characters basically JSON blobs we could have the process of moving them from the available list to the encounter list random 20 and add the creature.goblin.init, or whatever and set that variable automagically.  

I think having this as an optional feature. I can see some DMs wanting to have a greater deal of control in the initiative order. Of course, they can always modify the scores as they see fit when the encounter creation is done.
